---
name: Execute tests and linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yaml
    secrets: inherit
    with:
      run-codecov: true
