---
name: Publish

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yaml
    secrets: inherit

  pypi-publish:
    needs: ci
    name: upload release to PyPI
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Create files
        run: |
          pip install tox
          tox -e build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  docs-publish:
    needs: ci
    name: publish documentation to Read the Docs
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Trigger Read the Docs build
        env:
          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
        run: |
          curl --fail-with-body -X POST \
            -H "Authorization: Token ${READTHEDOCS_TOKEN}" \
            "https://readthedocs.org/api/v3/projects/aioafero/versions/latest/builds/"
